### ISSUE TITLE
Installing “codelf@0.3.0” failed.

### ISSUE THREAD

**Issue by anxsec** [unbug/atom-codelf#1]
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Linux 4.2.0-25-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.5" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure" "--proxy=http://hk1.dig.name:25/"
gyp ERR! cwd /home/anx/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by unbug** [comment]
can you try to install it from Atom Setting?

**Comment by anxsec** [comment]
哥们我就是从setting里安装的

**Comment by unbug** [comment]
奇怪，你的错误并没有与Codelf相关的，你是ubuntu吗？我还真资源测试这个平台

**Comment by anxsec** [comment]
```
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
```

我之前安装其他插件也没遇到过，google了一下没找到解决办法。

**Comment by unbug** [comment]
Atom升级很快，可能是你的node版本过低了，你试试换到最稳定的0.12.X看看

**Comment by anxsec** [comment]
好的，今天我用包管理器升级了一下atom，确实是我的问题，谢谢 :-)

**Comment by unbug** [comment]
哈哈，好用不要忘了给同学们推荐哟 :)
