### ISSUE TITLE
i can't open it on atom,and hapen this issue:

### ISSUE THREAD

**Issue by 656025633** [unbug/atom-codelf#3]
Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/atom-codelf-3.8.0/lib/MainView.coffee:1:13)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/atom-codelf-3.8.0/lib/MainView.coffee:1:1)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/atom-codelf-3.8.0/index.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/atom-codelf-3.8.0/index.coffee:1:1)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\package.js:741:27)
    at Package.module.exports.Package.activateNow (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\package.js:174:16)
    at C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\package.js:821:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\admin\AppData\Local\atom\app-1.12.6\resources\app.asar\src\command-registry.js:240:20)

**Comment by unbug** [comment]
Can you try to re-install Codelf or re-install Atom then re-install Codelf?
I just tested it, it's working fine with the latest Atom.
